<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGWULl83\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGWULl83/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGWULl83.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGWULl83\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGWULl83\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GWULl83',
    'container.build_id' => 'dcb5649c',
    'container.build_time' => 1636729901,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGWULl83');
