<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6mxcY30\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6mxcY30/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6mxcY30.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6mxcY30\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6mxcY30\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6mxcY30',
    'container.build_id' => 'c2cb3d40',
    'container.build_time' => 1636628439,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6mxcY30');
