<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLrptADW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLrptADW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLrptADW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLrptADW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLrptADW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LrptADW',
    'container.build_id' => '30ddb439',
    'container.build_time' => 1636197894,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLrptADW');
